export default {
  login: "Jeetanshu",
  id: 57320678,
  node_id: "MDQ6VXNlcjU3MzIwNjc4",
  avatar_url: "https://avatars.githubusercontent.com/u/57320678?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Jeetanshu",
  html_url: "https://github.com/Jeetanshu",
  followers_url: "https://api.github.com/users/Jeetanshu/followers",
  following_url:
    "https://api.github.com/users/Jeetanshu/following{/other_user}",
  gists_url: "https://api.github.com/users/Jeetanshu/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Jeetanshu/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Jeetanshu/subscriptions",
  organizations_url: "https://api.github.com/users/Jeetanshu/orgs",
  repos_url: "https://api.github.com/users/Jeetanshu/repos",
  events_url: "https://api.github.com/users/Jeetanshu/events{/privacy}",
  received_events_url: "https://api.github.com/users/Jeetanshu/received_events",
  type: "User",
  site_admin: false,
  name: "Jeetanshu Srivastava",
  company: null,
  blog: "",
  location: "India",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 41,
  public_gists: 0,
  followers: 7,
  following: 8,
  created_at: "2019-11-03T13:49:23Z",
  updated_at: "2022-12-10T10:42:50Z",
};
