export default [
  {
    login: "legitbeep",
    id: 50167891,
    node_id: "MDQ6VXNlcjUwMTY3ODkx",
    avatar_url: "https://avatars.githubusercontent.com/u/50167891?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/legitbeep",
    html_url: "https://github.com/legitbeep",
    followers_url: "https://api.github.com/users/legitbeep/followers",
    following_url:
      "https://api.github.com/users/legitbeep/following{/other_user}",
    gists_url: "https://api.github.com/users/legitbeep/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/legitbeep/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/legitbeep/subscriptions",
    organizations_url: "https://api.github.com/users/legitbeep/orgs",
    repos_url: "https://api.github.com/users/legitbeep/repos",
    events_url: "https://api.github.com/users/legitbeep/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/legitbeep/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mr-joshi",
    id: 56737320,
    node_id: "MDQ6VXNlcjU2NzM3MzIw",
    avatar_url: "https://avatars.githubusercontent.com/u/56737320?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mr-joshi",
    html_url: "https://github.com/mr-joshi",
    followers_url: "https://api.github.com/users/mr-joshi/followers",
    following_url:
      "https://api.github.com/users/mr-joshi/following{/other_user}",
    gists_url: "https://api.github.com/users/mr-joshi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mr-joshi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mr-joshi/subscriptions",
    organizations_url: "https://api.github.com/users/mr-joshi/orgs",
    repos_url: "https://api.github.com/users/mr-joshi/repos",
    events_url: "https://api.github.com/users/mr-joshi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mr-joshi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "krishnajalan",
    id: 69248796,
    node_id: "MDQ6VXNlcjY5MjQ4Nzk2",
    avatar_url: "https://avatars.githubusercontent.com/u/69248796?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/krishnajalan",
    html_url: "https://github.com/krishnajalan",
    followers_url: "https://api.github.com/users/krishnajalan/followers",
    following_url:
      "https://api.github.com/users/krishnajalan/following{/other_user}",
    gists_url: "https://api.github.com/users/krishnajalan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/krishnajalan/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/krishnajalan/subscriptions",
    organizations_url: "https://api.github.com/users/krishnajalan/orgs",
    repos_url: "https://api.github.com/users/krishnajalan/repos",
    events_url: "https://api.github.com/users/krishnajalan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/krishnajalan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sarthakastic",
    id: 72138026,
    node_id: "MDQ6VXNlcjcyMTM4MDI2",
    avatar_url: "https://avatars.githubusercontent.com/u/72138026?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sarthakastic",
    html_url: "https://github.com/sarthakastic",
    followers_url: "https://api.github.com/users/sarthakastic/followers",
    following_url:
      "https://api.github.com/users/sarthakastic/following{/other_user}",
    gists_url: "https://api.github.com/users/sarthakastic/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sarthakastic/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/sarthakastic/subscriptions",
    organizations_url: "https://api.github.com/users/sarthakastic/orgs",
    repos_url: "https://api.github.com/users/sarthakastic/repos",
    events_url: "https://api.github.com/users/sarthakastic/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sarthakastic/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "shivam956",
    id: 73737446,
    node_id: "MDQ6VXNlcjczNzM3NDQ2",
    avatar_url: "https://avatars.githubusercontent.com/u/73737446?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/shivam956",
    html_url: "https://github.com/shivam956",
    followers_url: "https://api.github.com/users/shivam956/followers",
    following_url:
      "https://api.github.com/users/shivam956/following{/other_user}",
    gists_url: "https://api.github.com/users/shivam956/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/shivam956/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/shivam956/subscriptions",
    organizations_url: "https://api.github.com/users/shivam956/orgs",
    repos_url: "https://api.github.com/users/shivam956/repos",
    events_url: "https://api.github.com/users/shivam956/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/shivam956/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "DADDY-DOUBLESHOT",
    id: 78498799,
    node_id: "MDQ6VXNlcjc4NDk4Nzk5",
    avatar_url: "https://avatars.githubusercontent.com/u/78498799?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/DADDY-DOUBLESHOT",
    html_url: "https://github.com/DADDY-DOUBLESHOT",
    followers_url: "https://api.github.com/users/DADDY-DOUBLESHOT/followers",
    following_url:
      "https://api.github.com/users/DADDY-DOUBLESHOT/following{/other_user}",
    gists_url: "https://api.github.com/users/DADDY-DOUBLESHOT/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/DADDY-DOUBLESHOT/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/DADDY-DOUBLESHOT/subscriptions",
    organizations_url: "https://api.github.com/users/DADDY-DOUBLESHOT/orgs",
    repos_url: "https://api.github.com/users/DADDY-DOUBLESHOT/repos",
    events_url:
      "https://api.github.com/users/DADDY-DOUBLESHOT/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/DADDY-DOUBLESHOT/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Himans05",
    id: 99680395,
    node_id: "U_kgDOBfEAiw",
    avatar_url: "https://avatars.githubusercontent.com/u/99680395?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Himans05",
    html_url: "https://github.com/Himans05",
    followers_url: "https://api.github.com/users/Himans05/followers",
    following_url:
      "https://api.github.com/users/Himans05/following{/other_user}",
    gists_url: "https://api.github.com/users/Himans05/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Himans05/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Himans05/subscriptions",
    organizations_url: "https://api.github.com/users/Himans05/orgs",
    repos_url: "https://api.github.com/users/Himans05/repos",
    events_url: "https://api.github.com/users/Himans05/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Himans05/received_events",
    type: "User",
    site_admin: false,
  },
];
